# Generated by Django 2.0.13 on 2020-10-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersCropDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=100)),
                ('selleremail', models.CharField(max_length=100)),
                ('cropname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100000)),
                ('file', models.FileField(upload_to='files/')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Farmerscroptable',
            },
        ),
        migrations.CreateModel(
            name='FarmersCropsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=100)),
                ('selleremail', models.CharField(max_length=100)),
                ('cropname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100000)),
                ('file', models.FileField(upload_to='files/')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FarmersCrops',
            },
        ),
    ]
